In [15]:
import pandas as pd
from pathlib import Path
from sklearn.model_selection import train_test_split

In [16]:
# pd.read_csv("D:\datasets\Fashion")
dataset = Path(r"D:\datasets\Fashion")

In [17]:
for file in dataset.iterdir():
    print("file", file)

file D:\datasets\Fashion\fashion-mnist_test.csv
file D:\datasets\Fashion\fashion-mnist_train.csv
file D:\datasets\Fashion\t10k-images-idx3-ubyte
file D:\datasets\Fashion\t10k-labels-idx1-ubyte
file D:\datasets\Fashion\train-images-idx3-ubyte
file D:\datasets\Fashion\train-labels-idx1-ubyte

In [18]:
train_dataset = dataset / "fashion-mnist_train.csv"
print("train_dataset", train_dataset)

train_dataset D:\datasets\Fashion\fashion-mnist_train.csv

In [19]:
train_df = pd.read_csv(train_dataset)

# for file in train_dataset.iterdir():
#     print(file)

In [20]:
train_df

,label,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,pixel9,...,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783,pixel784
0,2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,9,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,6,0,0,0,0,0,0,0,5,0,...,0,0,0,30,43,0,0,0,0,0
3,0,0,0,0,1,2,0,0,0,0,...,3,0,0,0,0,1,0,0,0,0
4,3,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59995,9,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
59996,1,0,0,0,0,0,0,0,0,0,...,73,0,0,0,0,0,0,0,0,0
59997,8,0,0,0,0,0,0,0,0,0,...,160,162,163,135,94,0,0,0,0,0
59998,8,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
59999,7,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [21]:
train_df.shape

(60000, 785)

In [22]:
train_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 60000 entries, 0 to 59999
Columns: 785 entries, label to pixel784
dtypes: int64(785)
memory usage: 359.3 MB

In [23]:
train_df.describe().T

            count       mean        std  min  25%  50%  75%    max
label     60000.0   4.500000   2.872305  0.0  2.0  4.5  7.0    9.0
pixel1    60000.0   0.000900   0.094689  0.0  0.0  0.0  0.0   16.0
pixel2    60000.0   0.006150   0.271011  0.0  0.0  0.0  0.0   36.0
pixel3    60000.0   0.035333   1.222324  0.0  0.0  0.0  0.0  226.0
pixel4    60000.0   0.101933   2.452871  0.0  0.0  0.0  0.0  164.0
...           ...        ...        ...  ...  ...  ...  ...    ...
pixel780  60000.0  17.911483  45.149388  0.0  0.0  0.0  0.0  255.0
pixel781  60000.0   8.520633  29.614859  0.0  0.0  0.0  0.0  255.0
pixel782  60000.0   2.753300  17.397652  0.0  0.0  0.0  0.0  255.0
pixel783  60000.0   0.855517   9.356960  0.0  0.0  0.0  0.0  255.0
pixel784  60000.0   0.070250   2.125870  0.0  0.0  0.0  0.0  170.0

[785 rows x 8 columns]

In [24]:
train_df.head(10)

,label,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,pixel9,...,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783,pixel784
0,2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,9,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,6,0,0,0,0,0,0,0,5,0,...,0,0,0,30,43,0,0,0,0,0
3,0,0,0,0,1,2,0,0,0,0,...,3,0,0,0,0,1,0,0,0,0
4,3,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5,4,0,0,0,5,4,5,5,3,5,...,7,8,7,4,3,7,5,0,0,0
6,4,0,0,0,0,0,0,0,0,0,...,14,0,0,0,0,0,0,0,0,0
7,5,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
8,4,0,0,0,0,0,0,3,2,0,...,1,0,0,0,0,0,0,0,0,0
9,8,0,0,0,0,0,0,0,0,0,...,203,214,166,0,0,0,0,0,0,0

In [26]:
train_x = train_df.drop("label", axis=1)
train_y = train_df["label"]
train_y

0        2
1        9
2        6
3        0
4        3
        ..
59995    9
59996    1
59997    8
59998    8
59999    7
Name: label, Length: 60000, dtype: int64

In [27]:
train_x.head(10)

,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,pixel9,pixel10,...,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783,pixel784
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,5,0,0,...,0,0,0,30,43,0,0,0,0,0
3,0,0,0,1,2,0,0,0,0,0,...,3,0,0,0,0,1,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5,0,0,0,5,4,5,5,3,5,6,...,7,8,7,4,3,7,5,0,0,0
6,0,0,0,0,0,0,0,0,0,0,...,14,0,0,0,0,0,0,0,0,0
7,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
8,0,0,0,0,0,0,3,2,0,0,...,1,0,0,0,0,0,0,0,0,0
9,0,0,0,0,0,0,0,0,0,0,...,203,214,166,0,0,0,0,0,0,0

In [28]:
X_train, X_Val, Y_train, Y_Val = train_test_split(
    train_x,
    train_y,
    random_state=42,
    test_size=0.1,
    stratify=train_y
)

In [33]:
X_train.shape, Y_train.shape

((54000, 784), (54000,))

In [34]:
X_Val.shape, Y_Val.shape

((6000, 784), (6000,))

In [35]:
X_train

,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,pixel9,pixel10,...,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783,pixel784
36365,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
15439,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
41209,0,0,0,0,0,0,0,125,220,229,...,8,4,0,0,0,0,0,0,0,0
52146,0,0,0,1,0,2,0,0,0,0,...,103,23,0,0,1,0,0,0,0,0
7892,0,0,0,0,0,0,0,0,0,8,...,37,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31830,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
56755,0,0,0,0,0,0,0,0,0,36,...,183,102,0,0,0,0,0,0,0,0
38134,0,0,2,0,20,51,47,59,79,97,...,37,8,0,0,0,0,2,0,0,0
53447,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
55248,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [36]:
X_train.isnull().sum()

pixel1      0
pixel2      0
pixel3      0
pixel4      0
pixel5      0
           ..
pixel780    0
pixel781    0
pixel782    0
pixel783    0
pixel784    0
Length: 784, dtype: int64

In [38]:
X_train.describe().T

            count       mean        std  min  25%  50%  75%    max
pixel1    54000.0   0.000981   0.099718  0.0  0.0  0.0  0.0   16.0
pixel2    54000.0   0.005759   0.243024  0.0  0.0  0.0  0.0   36.0
pixel3    54000.0   0.032667   0.841901  0.0  0.0  0.0  0.0  106.0
pixel4    54000.0   0.102019   2.493841  0.0  0.0  0.0  0.0  164.0
pixel5    54000.0   0.243444   4.224815  0.0  0.0  0.0  0.0  227.0
...           ...        ...        ...  ...  ...  ...  ...    ...
pixel780  54000.0  17.890870  45.122053  0.0  0.0  0.0  0.0  255.0
pixel781  54000.0   8.496463  29.571109  0.0  0.0  0.0  0.0  255.0
pixel782  54000.0   2.769389  17.474738  0.0  0.0  0.0  0.0  255.0
pixel783  54000.0   0.873574   9.433927  0.0  0.0  0.0  0.0  255.0
pixel784  54000.0   0.072407   2.183158  0.0  0.0  0.0  0.0  170.0

[784 rows x 8 columns]

In [40]:
X_train.duplicated().sum()

np.int64(35)

In [44]:
X_train.drop_duplicates()

,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,pixel9,pixel10,...,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783,pixel784
36365,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
15439,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
41209,0,0,0,0,0,0,0,125,220,229,...,8,4,0,0,0,0,0,0,0,0
52146,0,0,0,1,0,2,0,0,0,0,...,103,23,0,0,1,0,0,0,0,0
7892,0,0,0,0,0,0,0,0,0,8,...,37,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31830,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
56755,0,0,0,0,0,0,0,0,0,36,...,183,102,0,0,0,0,0,0,0,0
38134,0,0,2,0,20,51,47,59,79,97,...,37,8,0,0,0,0,2,0,0,0
53447,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
55248,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [47]:
X_train.shape

(54000, 784)